version: '3'
services:
  bc-vd-publisher:
    build:
      context: .
      dockerfile: ./docker/bc/Dockerfile
    image: vd-bc-publisher:latest
    container_name: bc-vd-publisher
    restart: always
    volumes:
      - "./config/bc:/home/node/app/config"
      - "publisher-data:/home/node/app/data"
    network_mode: host
    env_file:
      - ".env"

volumes:
  publisher-data:
    driver: local
